# Simple node.js consumer
FROM node:18

# Working directory for your project
WORKDIR /app

# Copy your project files
COPY . /app

# Install required dependencies (replace with your actual dependencies)
RUN npm install

# Start an interactive bash session
CMD ["node", "main.js"]